server:
  port: 8080

spring:
  datasource:
    url: r2dbc:pool:postgres://localhost:5432/Event_aggregator
#    url: jdbc:postgresql://localhost:5432/Event_aggregator
    username: postgres
    password: rootroot1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEV8X43g
      iteration: 64
      keylength: 256
  secret:
  lifetime: 30m
